### ISSUE TITLE
BedEnterListener.java: Find a way to store these variables elsewhere(Possibly a Configuration Handler class)

### ISSUE THREAD

**Issue by AGunnarP** [AidSucks/OnePlayerSleep#1]
OnePlayerSleepPlugin/src/aid/me/ops/sleep/BedEnterListener.java

![Issue](https://user-images.githubusercontent.com/53379060/73599309-d5554400-44f6-11ea-89d9-99878969609b.JPG)

Need to find a more optimal way to hold variables defined in comment.

**Comment by retro-aid** [comment]
I was actually planning on making a PlayerData class object that will store all the necessary player info to be used in many different classes, I haven't gotten around to that tho

**Comment by retro-aid** [comment]
ConfigurationManager class and PlayerData class now created in version 2.7 branch! Should solve this issue
