### ISSUE TITLE
Does not work in 1.16.4

### ISSUE THREAD

**Issue by Jakeahorner** [AidSucks/OnePlayerSleep#5]
It seems to just spam the console in 1.16.4 due to not being able to pass the PlayerBedEnterEvent

**Comment by retro-aid** [comment]
Are you referring to the repository's code or the plugin from GitHub? Because the repository's code is behind the release on SpigotMc, but the relase on SpigotMc should work.

**Comment by retro-aid** [comment]
Nevermind, turns out the plugin was in fact out of date, the most recent update should fix this. Thank you!
