### ISSUE TITLE
No Installation instructions

### ISSUE THREAD

**Issue by ToasterUwU** [AidSucks/OnePlayerSleep#7]
Would be nice if you could provide a "How to use" in the README.md

Right now, I see a folder that doesn't load as a plugin if I add it to the server.
Im only used to have a .jar file. So would be nice if you make it a .jar and add an installation instruction.

**Comment by retro-aid** [comment]
> Would be nice if you could provide a "How to use" in the README.md
> 
> 
> 
> Right now, I see a folder that doesn't load as a plugin if I add it to the server.
> 
> Im only used to have a .jar file. So would be nice if you make it a .jar and add an installation instruction.

Hello! Thanks for the suggestion! However, I'm unsure whether you need the plugin's jar file, or the Spigot API jar file. The downlod for the plugin's jar file can be found [here](https://www.spigotmc.org/resources/one-player-sleep.45607/)
However, Spigot's api can be found on their website. I'll definitely add some instructions in the readme, but I hope that this helped.
Thanks, Aid.

**Comment by ToasterUwU** [comment]
Thats the link that i needed. 

Would be nice if you can add a ".jar file can be found here" to the README.md and/or add the .jar file to the release (since that is what this feature is for)

Thanks anyways, everything works now. Have a nice day!

**Comment by retro-aid** [comment]
No problem! Glad I could help. I'll update the readme file as soon as I can. :)
